# Automatically generated by configure - do not modify
SRC_PATH=/home/max/esp32-fuzzing-framework/qemu/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
